# Generated by Django 6.0.3 on 2026-03-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='moImage.png', upload_to=''),
        ),
    ]
